CREATE TABLE IF NOT EXISTS users (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	login CHAR(128),
	password VARCHAR(128),
	rooms int[],
	chats int[]
);

CREATE TABLE IF NOT EXISTS chatroom (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	chatname VARCHAR(255) NOT NULL,
	chatowner_id BIGINT NOT NULL,
	CONSTRAINT fk_chat_user FOREIGN KEY (chatowner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS messages (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	author_id BIGINT NOT NULL,
	room_id BIGINT NOT NULL,
	text VARCHAR,
	date TIMESTAMP,
	CONSTRAINT fk_author_users FOREIGN KEY (author_id) REFERENCES users(id),
	CONSTRAINT fk_room_chatroom FOREIGN KEY (room_id) REFERENCES chatroom(id)
);


